############################################################
# +------------------------------------------------------+ #
# |             CustomPrefix Config File                 | #
# +------------------------------------------------------+ #
############################################################

# Configuration file for CustomPrefix
# Plugin developed by millenium200

# These commands are executed to set and reset prefixes.  {PLAYER} is a variable
# for the playername whose prefix is being set and {PREFIX} is a variable for the prefix  
setprefixcommand: pex user {PLAYER} prefix "{PREFIX}"
resetprefixcommand: pex user {PLAYER} prefix ""

# This is the maximum length of the prefix.  Note, this does not include formatting
# The maximul length of prefixes including formatting (ie. &2) is 14 characters.
maxPrefixLength: 8

# Specify who you want prefixes to be sent to here.  The default
# is millenium200 (dev).
sendPrefixesTo: millenium200

# These allow you to customize the format of the brackets for prefixes
startingBracket: '&8&l[&5&l'
closingBracket: '&8&l] &5&l'

# To add to this list, check http://minecraft.gamepedia.com/Formatting_codes#Color_codes
# and add the code (only the letter) to the following list
# By default, &4 (dark red) and &c (red) are blocked
bannedcolors:
  - '4'
  - 'c'

# Here, you can add words to be blocked in prefixes
# To add to this list, keep spacing and add "  - word" where word
# is the word you want to block.
bannedwords:
  - admin
  - owner
  - helper
  - mod
  - dev
  - architect
  - head
  - nig
  - fag
  - shit
  - penis
  - dick
  - fuc
  - anus
  - ass
  - arse
  - bastard
  - bitch
  - boner
  - butt
  - blowjob
  - beaner
  - bampot
  - cunt
  - cock
  - cum
  - dike
  - douche
  - fellatio
  - damn
  - kike
  - kraut
  - paki
  - vag
  - pussies
  - lick
  - suck
  - queer
  - slut
  - tard
  - testicle
  - twat
  - wank
  - whore
  - wop
  - fuk
  - sh1t
  - hoe
  - shiz
  - fak
  - fek
  - coon
  - crack
  - honky
  - jew
  - wog
  - tit

