############################################################
# +------------------------------------------------------+ #
# |             CustomPrefix Config File                 | #
# +------------------------------------------------------+ #
############################################################

# Configuration file for CustomPrefix
# Plugin developed by millenium200

# Here, you can add words to be blocked in
# the prefixes.

bannedwords:
  - test1
  - test2
  - yolo

# This is the maximum length of the prefix.  Note, this does
# not include &'s.  The maximum length of the prefix and the
# &'s is 14.
maxPrefixLength: 8