name: CustomPrefix
main: com.gmail.moonmasters200.CustomPrefix.Main
version: 0.0.6-SWAG
author: millenium200 & moppletop
commands:
  prefix:
    description: This command changes your prefix.
    usage: /<command> <set/reset> [prefix]
    permission: millenium.prefix.use
    permission-message: You don't have enough swag.
permissions:
    millenium.*:
        description: Gives access to all millenium perms
        children:
            millenium.prefix.use: true
    millenium.prefix.use:
        description: Allows you to use the command
        default: false