name: CustomPrefix
main: com.gmail.moonmasters200.CustomPrefix.Main
version: 0.0.35
author: millenium200
commands:
  prefix:
    description: This command changes your prefix.
    usage: /prefix [set <prefix> [username] | check <username> | reset [username] | reloadconfig]
    permission: millenium.prefix.use
    permission-message: You don't have enough swag.
permissions:
    millenium.prefix.*:
        description: Gives access to all millenium perms
        children:
            millenium.prefix.admin: true
            millenium.prefix.use: true
            millenium.prefix.reload: true
    millenium.prefix.admin:
        description: Gives access to all admin commands of prefix
        children:
            millenium.prefix.resetothers: true
            millenium.prefix.setothers: true
            millenium.prefix.check: true
    millenium.prefix.setothers:
        description: Allows access to set others' prefixes
    milenium.prefix.resetothers:
        description: Allows access to reset others' prefixes
    millenium.prefix.check:
        description: Allows you to check prefixes
    millenium.prefix.use:
        description: Allows you to use the command
        default: false
    millenium.prefix.reload:
        description: Allows you to reload the config
        default: op