name: CustomPrefix
main: com.gmail.moonmasters200.CustomPrefix.Main
version: 0.0.23
author: millenium200 & moppletop
commands:
  prefix:
    description: This command changes your prefix.
    usage: /<command> <set> <prefix>
    permission: millenium.prefix.use
    permission-message: You don't have enough swag.
  prefixreset:
    description: This command resets your prefix.
    usage: /<command>
    permission: millenium.prefix.use
    permission-message: You don't have enough swag.
  resetprefix:
    description: This command resets your prefix.
    usage: /<command>
    permission: millenium.prefix.use
    permission-message: You don't have enough swag.
permissions:
    millenium.*:
        description: Gives access to all millenium perms
        children:
            millenium.prefix.use: true
    millenium.prefix.use:
        description: Allows you to use the command
        default: false